### ISSUE TITLE
Sketch not working

### ISSUE THREAD

**Issue by OscarBaksa** [newgnu/attiny85_slots#1]
Tried to compile the sketch but I have this errors:
SoftWire.h:113:20: error: conflicting return type specified for 'virtual size_t SoftWire::write(const uint8_t*, size_t)'
     virtual size_t write(const uint8_t *data, size_t quantity);
Some help ?
Regards

**Comment by newgnu** [comment]
more info in https://github.com/newgnu/attiny85_slots/issues/2
